# T-Ruby RuboCop Configuration
# https://docs.rubocop.org/rubocop/

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'build/**/*'
    - 'vendor/**/*'
    - 'wasm/**/*'
    - 'docs/**/*'
    - 'editors/**/*'
    - 'examples/**/*'

# Layout
Layout/LineLength:
  Max: 150
  AllowedPatterns:
    - '^\s*#'  # Allow long comments
    - 'https?://'  # Allow URLs

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Metrics
Metrics/MethodLength:
  Max: 100
  CountAsOne:
    - array
    - hash
    - heredoc
  Exclude:
    - "scripts/**/*"

Metrics/BlockNesting:
  Exclude:
    - "scripts/**/*"
    - "lib/**/*"

Metrics/ClassLength:
  Max: 750

Metrics/ModuleLength:
  Max: 700

Metrics/AbcSize:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 35

Metrics/PerceivedComplexity:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
    - "Rakefile"
    - "lib/**/*"

Metrics/ParameterLists:
  Max: 8

# Naming
Naming/MethodParameterName:
  MinNameLength: 1

Security/Eval:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 5

Style/IfUnlessModifier:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

# Lint
Lint/MissingSuper:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"

Lint/EmptyBlock:
  Exclude:
    - "spec/**/*"

Lint/Void:
  Exclude:
    - "scripts/**/*"

Lint/DuplicateBranch:
  Enabled: false

Lint/DeprecatedConstants:
  Exclude:
    - "lib/t_ruby/smt_solver.rb"

# Style exceptions for specs
Style/StringConcatenation:
  Exclude:
    - "spec/**/*"

Style/MultilineBlockChain:
  Exclude:
    - "spec/**/*"

Naming/AccessorMethodName:
  Exclude:
    - "spec/**/*"
    - "lib/t_ruby/benchmark.rb"

Naming/PredicateMethod:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - "lib/t_ruby/benchmark.rb"

